site_name: tasat31 
site_description: Electromagnetic Radiated Over the World Enrichs our Lives.

repo_url: https://github.com/tasat31

theme:
  name: 'material'
  palette:
    primary: 'Orange'
    accent: 'Light Blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'radio'

pages:
  - Home: 'index.md'
  - 'Guide Book':
    - 'Python and Django'  : 'django/index.md'
    - 'OSMC on Raspberry Pi'  : 'osmc/index.md'
    - 'ARM and Accelerator' : 'armaccel/index.md'
    - 'Open Source CPU': 'openrisc/index.md'
    - 'SDR as Cognitive machines'     : 'sdr/index.md'

  - Appendix:
    - 'Quick reference for Web design': appendix/webdesign/index.md
    - 'RLT-SDR and LuaRadio': appendix/luasdr/index.md
    - 'Radio Communicaiton Technology': appendix/radiotech/index.md

  - About: 'about.md'

