site_name: tasat31 
nav:
  - Home: index.md
  - About: about.md
theme:
  name: 'material'
  palette:
    primary: 'Orange'
    accent: 'Light Blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'radio'
